In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
#pytorch
import torch as t
a=t.tensor([[1,2,3],[5,6,8]])
print("\n",a)
print(a.ndim)
print(a.shape)
print(a.numel())#here the it is a built in function
print(a.dtype)
print(a.device)


 tensor([[1, 2, 3],
        [5, 6, 8]])
2
torch.Size([2, 3])
6
torch.int64
cpu


In [3]:
import torch as t
print(t.ones((2,3),dtype=int))
print(t.zeros((2,3),dtype=int))
#Byte=8bits
#1kb=1024bytes
#1mb=1024kb
#1gb=1024mb
#1tb=1024gb
print(t.rand(2))#it is only the positive numbers
print(t.randn(2))#it is mixture of the positive and negative numbers



tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.4275, 0.6405])
tensor([1.3262, 0.9893])


In [4]:
import torch as t
a=t.tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)
print(a[1:3,:])
print(a[2,:])
print(a[1:3,1:2])
print(a[[0,1,2]])
print(a[[1,2],1])
print(a[:,2])
print(a[[0,1,2],2])
print(a[0:3,0])






tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([7, 8, 9])
tensor([[5],
        [8]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([5, 8])
tensor([3, 6, 9])
tensor([3, 6, 9])
tensor([1, 4, 7])


In [5]:
import torch as t
a=t.tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a[:,0])
print(a[:3,0])
print(a[:,0])
print(a[2:3,:3])
print(a[2:3,:])
print(a[2:,:3])
print(a[2:3,:3])


tensor([1, 4, 7])
tensor([1, 4, 7])
tensor([1, 4, 7])
tensor([[7, 8, 9]])
tensor([[7, 8, 9]])
tensor([[7, 8, 9]])
tensor([[7, 8, 9]])


In [6]:
import torch as t
a=t.tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])
b=t.tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(t.add(a,b))
print(a.sum())
print(t.sum(a))
print(t.subtract(a,b))
print(t.multiply(a,b))
print(t.divide(a,b))
print(t.max(a))
print(t.min(a))
print(t.max(b))
print(t.min(b))
print(t.argmax(a))
print(t.multiply(a,b))
print(t.matmul(a,b))


tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor(45)
tensor(45)
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor(9)
tensor(1)
tensor(9)
tensor(1)
tensor(8)
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [7]:
#booleam indixing
import torch as t
c=t.tensor([70,45,35,6])
i=print([c[c>50]])
print(c>50)
print(c>34)
print(c<50)




[tensor([70])]
tensor([ True, False, False, False])
tensor([ True,  True,  True, False])
tensor([False,  True,  True,  True])
